# Generated by Django 4.1 on 2022-08-11 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_message_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                related_name="participant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
