# Generated by Django 4.1 on 2022-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_rename_conversation_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media",
            field=models.FileField(null=True, upload_to="chat_media"),
        ),
    ]
