# Generated by Django 4.1 on 2022-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_message_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="chat_media"),
        ),
    ]
