# Generated by Django 4.1 on 2022-08-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_message_media"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ("-timestamp",)},
        ),
    ]
