# Generated by Django 4.1 on 2022-08-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_unread",
            field=models.BooleanField(default=True),
        ),
    ]
