# Generated by Django 4.1 on 2022-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_message_is_unread"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="thread_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
