# Generated by Django 4.1 on 2022-08-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_message_thread_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="thread_name",),
        migrations.AddField(
            model_name="conversations",
            name="thread_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
