# Generated by Django 4.1 on 2022-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_remove_message_thread_name_conversations_thread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images"
            ),
        ),
    ]
