# Generated by Django 4.1 on 2022-09-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(default="text", max_length=10),
        ),
    ]
