# Generated by Django 4.1 on 2022-09-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_message_message_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="message_type",),
    ]
