# Generated by Django 4.1 on 2022-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_remove_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_online",
            field=models.IntegerField(default=True),
        ),
    ]
