# Generated by Django 4.1 on 2022-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_alter_userprofile_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
