# Generated by Django 4.1.3 on 2022-11-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_alter_userprofile_is_online"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_online",),
    ]
